language: go

go:
  - 1.10.x
  - 1.11
  - 1.12
  - 1.13
env: 
  - GO111MODULE=on
install:
  - go get -t -v ./...

services:
  - mysql
  - postgresql

addons:
  - postgres: "9.6"

script:
  - go test -cover -v ./...

